Update colors
hacsoc/HackCWRU2016-Website pull request #34
Opened 2017-03-01 01:09 UTC by jcassarly

Heres a quick list of what I changed
EFEFEF [body, nav] -> E3E8EF - Tower City
045184 [nav text] -> 53595A - Steelyard Gray
3588CC [nav hover] -> 1371AC - edgewater blue
095790 [links in index.html] -> 023251 - Uptown Blue
095790 [faq] -> 1371AC - edgewater blue
C0C0C0 [not active] -> AFB9BC - Cleveland sky
1D86C8 [about, .reg, footer] -> 0F5D8D - Blue Line

2017-03-01 02:07 UTC, ajm188 requested changes

2017-03-01 02:07 UTC, ajm188 commented on www/index.html
> +				<h3>Lastly, at HackCWRU we abide by and enforce <a style="text-decoration: none; color:#023251;" href="http://static.mlh.io/docs/mlh-code-of-conduct.pdf">MLH's Code of Conduct</a>.</h3>
can we move this style to a CSS class?

2017-03-01 02:07 UTC, ajm188 commented on www/index.html
> +				<p><a style="color:#023251;" target="_blank" href="sponsor.pdf">Learn more about sponsoring HackCWRU</a><br>Interested?  Email <a style="color:#023251;" href="mailto:yxh597@case.edu">Yidi</a>!</p
ditto about classes here

2017-03-01 02:07 UTC, ajm188 commented on www/index.html
> +		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
what was the ":200" for and why did it get removed from the query param?

2017-03-01 02:18 UTC, jcassarly commented on www/index.html
> +		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
I dont actually know what that was, I didnt notice that when I was doing the editting, so ill just  add the ":200" after "Open+Sans"

2017-03-01 02:44 UTC, jcassarly commented
I think i made the changes requested.  I am not sure if the updates were actually applied to the pull request.

Also, I dont have a lot of experience with css and html, so it would be great if someone could make sure I created the css classes and used them right

2017-03-01 16:42 UTC, ajm188 requested changes
I think you messed up your git somehow, I would talk to someone at GB today to help you out, or find me in the slack

2017-03-01 16:42 UTC, ajm188 commented on www/index.html
> +<<<<<<< HEAD
you've got some leftovers of a git conflict here

2017-03-01 16:42 UTC, ajm188 commented on www/index.html
> +=======
and here

2017-03-01 16:42 UTC, ajm188 commented on www/index.html
> +                <!--				<li><a href="#schedule">Schedule</a></li>-->
can we remove this comment?

2017-03-01 16:42 UTC, ajm188 commented on www/index.html
> +        <!--<div id="schedule">
ditto, remove this commented out junk

2017-03-01 16:42 UTC, ajm188 commented on www/index.html
> +           <!--<div class="home_sponsors_logos">
remove comments

2017-03-01 16:42 UTC, ajm188 commented on www/site.css
> +<<<<<<< HEAD
git conflict leftovers (GCL)

2017-03-01 16:42 UTC, ajm188 commented on www/index.html
> +>>>>>>> 29aae13... added ":200" back to link and moved some styling to css classes
git conflict leftovers

2017-03-01 16:42 UTC, ajm188 commented on www/site.css
> +=======
GCL

2017-03-01 16:42 UTC, ajm188 commented on www/site.css
> +>>>>>>> 29aae13... added ":200" back to link and moved some styling to css classes
GCL

2017-03-03 18:20 UTC, jcassarly commented
I fixed the git conflicts, not sure what happened there

The comments were there before Is tarted updating colors, I think they were commented out because we were not able to use those parts of the website yet, i.e. we haven't started allowing registration

2017-03-03 21:18 UTC, jcassarly commented
There are actually still some issues with the colors that i didnt realize, so I will go fix that

2017-03-03 22:53 UTC, jcassarly commented
The colors should be fixed and I added the logo on Frontify currently

2017-03-03 23:01 UTC, ajm188 requested changes

2017-03-03 23:01 UTC, ajm188 commented on www/Logo.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 449.81 509.53"><defs><style>.cls-1{fill:none;}.cls-2{fill:#0a304f;}.cl
missing newline at EOF

2017-03-03 23:01 UTC, ajm188 commented on www/index.html
> -              <!--				<li><a href="#schedule">Schedule</a></li>-->
either delete this comment, or revert this change; git churn--

2017-03-03 23:01 UTC, ajm188 commented on www/index.html
> +				<h3>Lastly, at HackCWRU we abide by and enforce <a class="link_text_1" href="http://static.mlh.io/docs/mlh-code-of-conduct.pdf">MLH's Code of Conduct</a>.</h3>
can we use more descriptive class names?

2017-03-03 23:01 UTC, ajm188 commented on www/index.html
> +				<p>Learn more about sponsoring HackCWRU<br>Interested?  Email <a class="link_text_2" href="mailto:bgr19@case.edu">Ben</a>!</p>
ditto on descriptive class names

2017-03-03 23:01 UTC, ajm188 commented on www/site.css
> -body {
please revert the indentation-only changes to this file

2017-03-06 18:22 UTC, jcassarly commented on www/site.css
> -body {
I am not sure exactly what to do here, should I change the tabs to spaces?

2017-03-06 18:24 UTC, jcassarly commented
I changed the image back as per Yidi's request

2017-03-06 18:43 UTC, ajm188 commented on www/site.css
> -body {
Yes, we use spaces for indentation

2017-03-06 18:47 UTC, jcassarly commented on www/site.css
> -body {
ok, not sure why that was, I think that the file I cloned was like that

2017-03-06 19:14 UTC, ajm188 commented on www/site.css
> -body {
no, most likely a side effect of your editor rewriting the file

2017-04-10 17:52 UTC, closed without merging

2017-04-10 18:32 UTC, ajm188 commented
@jcassarly if we're not merging this, is it safe for me to delete the branch?

2017-04-10 19:13 UTC, jcassarly commented
Should be

On Apr 10, 2017 2:40 PM, "Andrew Mason" <notifications@github.com> wrote:

@jcassarly <https://github.com/jcassarly> if we're not merging this, is it
safe for me to delete the branch?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/hacsoc/HackCWRU2016-Website/pull/34#issuecomment-293038578>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AVHDmaNokkDesQd1M8VgH72sHfvQLGy4ks5runW8gaJpZM4MPGCs>
.

2017-04-10 19:14 UTC, ajm188 commented
Deleted